[2025-03-18T10:10:22.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-18T10:10:22.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T09:00:00+00:00 [queued]>
[2025-03-18T10:10:22.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T09:00:00+00:00 [queued]>
[2025-03-18T10:10:22.352+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-18T10:10:22.366+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-18 09:00:00+00:00
[2025-03-18T10:10:22.379+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_etl_dag', 'transform_data', 'scheduled__2025-03-18T09:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp38tog_d4']
[2025-03-18T10:10:22.382+0000] {standard_task_runner.py:91} INFO - Job 268: Subtask transform_data
[2025-03-18T10:10:22.383+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=96962) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T10:10:22.384+0000] {standard_task_runner.py:63} INFO - Started process 96981 to run task
[2025-03-18T10:10:22.435+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T09:00:00+00:00 [running]> on host 23e83e453497
[2025-03-18T10:10:22.516+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T09:00:00+00:00'
[2025-03-18T10:10:22.517+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-18T10:10:22.601+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T10:10:24.103+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T10:10:26.072+0000] {logging_mixin.py:188} INFO - Random Forest MSE: 434750610.19154423 - R²: 0.499567642944985
[2025-03-18T10:10:26.072+0000] {logging_mixin.py:188} INFO - XGBoost MSE: 575514269.4017029 - R²: 0.3375375316239392
[2025-03-18T10:10:26.092+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/transform.py:88 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-18T10:10:26.115+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-18T10:10:26.116+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-18T10:10:26.124+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_etl_dag, task_id=transform_data, run_id=scheduled__2025-03-18T09:00:00+00:00, execution_date=20250318T090000, start_date=20250318T101022, end_date=20250318T101026
[2025-03-18T10:10:26.146+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-18T10:10:26.169+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-18T10:10:26.172+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
