[2025-03-18T16:36:24.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-18T16:36:24.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T15:00:00+00:00 [queued]>
[2025-03-18T16:36:24.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T15:00:00+00:00 [queued]>
[2025-03-18T16:36:24.997+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-18T16:36:25.009+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-18 15:00:00+00:00
[2025-03-18T16:36:25.022+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_etl_dag', 'transform_data', 'scheduled__2025-03-18T15:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp99pwlujd']
[2025-03-18T16:36:25.024+0000] {standard_task_runner.py:91} INFO - Job 276: Subtask transform_data
[2025-03-18T16:36:25.025+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=42047) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T16:36:25.025+0000] {standard_task_runner.py:63} INFO - Started process 42066 to run task
[2025-03-18T16:36:25.064+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T15:00:00+00:00 [running]> on host e8963d5c211f
[2025-03-18T16:36:25.130+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T15:00:00+00:00'
[2025-03-18T16:36:25.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-18T16:36:25.227+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T16:36:26.741+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T16:36:28.402+0000] {logging_mixin.py:188} INFO - Random Forest MSE: 457190325.0 - R²: 0.02466064000000001
[2025-03-18T16:36:28.403+0000] {logging_mixin.py:188} INFO - XGBoost MSE: 544040147.6804624 - R²: -0.16061898171831968
[2025-03-18T16:36:28.415+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/transform.py:88 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-18T16:36:28.437+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-18T16:36:28.438+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-18T16:36:28.446+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_etl_dag, task_id=transform_data, run_id=scheduled__2025-03-18T15:00:00+00:00, execution_date=20250318T150000, start_date=20250318T163624, end_date=20250318T163628
[2025-03-18T16:36:28.496+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-18T16:36:28.515+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-18T16:36:28.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
