[2025-03-19T04:27:29.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-19T04:27:29.600+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T16:00:00+00:00 [queued]>
[2025-03-19T04:27:29.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T16:00:00+00:00 [queued]>
[2025-03-19T04:27:29.608+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-19T04:27:29.620+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-18 16:00:00+00:00
[2025-03-19T04:27:29.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_etl_dag', 'transform_data', 'scheduled__2025-03-18T16:00:00+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpofqmyma7']
[2025-03-19T04:27:29.632+0000] {standard_task_runner.py:91} INFO - Job 284: Subtask transform_data
[2025-03-19T04:27:29.644+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=494) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T04:27:29.646+0000] {standard_task_runner.py:63} INFO - Started process 508 to run task
[2025-03-19T04:27:29.718+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T16:00:00+00:00 [running]> on host d95dc314d490
[2025-03-19T04:27:29.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T16:00:00+00:00'
[2025-03-19T04:27:29.821+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-19T04:27:29.889+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-19T04:27:31.803+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-19T04:27:45.542+0000] {logging_mixin.py:188} INFO - Random Forest MSE: 148274587.79945076 - R²: 0.7627606595208788
[2025-03-19T04:27:45.545+0000] {logging_mixin.py:188} INFO - XGBoost MSE: 173121578.84054804 - R²: 0.7230054738551231
[2025-03-19T04:27:45.559+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/transform.py:88 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-19T04:27:45.585+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-19T04:27:45.585+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-19T04:27:45.592+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_etl_dag, task_id=transform_data, run_id=scheduled__2025-03-18T16:00:00+00:00, execution_date=20250318T160000, start_date=20250319T042729, end_date=20250319T042745
[2025-03-19T04:27:45.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-19T04:27:45.646+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T04:27:45.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
